language: node_js
node_js:
  - "5"
services:
  - redis-server
after_script:
  - cat /home/travis/build/Alpha-Atom/uni-society-manager/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf /home/travis/build/Alpha-Atom/uni-society-manager/coverage/
